// <auto-generated />
using ConstellationGarage.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstellationGarage.Migrations
{
    [DbContext(typeof(GarageautomobileContext))]
    [Migration("20221220122409_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConstellationGarage.Models.Brand", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("PK__brands__357D4CF8C2528B45");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("ConstellationGarage.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeBrand")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code_brand");

                    b.Property<string>("CodeCategorie")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code_categorie");

                    b.Property<string>("Color")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("color");

                    b.Property<string>("Essence")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("essence");

                    b.HasKey("Id")
                        .HasName("PK__cars__3213E83F01802EF8");

                    b.HasIndex("CodeBrand");

                    b.HasIndex("CodeCategorie");

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("ConstellationGarage.Models.Category", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("PK__categori__357D4CF89E4D866F");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ConstellationGarage.Models.Car", b =>
                {
                    b.HasOne("ConstellationGarage.Models.Brand", "CodeBrandNavigation")
                        .WithMany("Cars")
                        .HasForeignKey("CodeBrand")
                        .HasConstraintName("FK__cars__code_brand__3D5E1FD2");

                    b.HasOne("ConstellationGarage.Models.Category", "CodeCategorieNavigation")
                        .WithMany("Cars")
                        .HasForeignKey("CodeCategorie")
                        .HasConstraintName("FK__cars__code_categ__3E52440B");

                    b.Navigation("CodeBrandNavigation");

                    b.Navigation("CodeCategorieNavigation");
                });

            modelBuilder.Entity("ConstellationGarage.Models.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("ConstellationGarage.Models.Category", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
